### ISSUE TITLE
Inconsistency age range

### ISSUE THREAD

**Issue by distantobserver** [Llewellynvdm/Joomla-Cost-Benefit-Projection#13]
I am working on Mycomp from clienta

As you can see from the below. They only have males age 35-39 and females 50-54

![image](https://cloud.githubusercontent.com/assets/7658109/15221775/baba3596-1864-11e6-9291-be908f0bae00.png)

However, when you look at the results section you can see work days lost for females age 35-39

![image](https://cloud.githubusercontent.com/assets/7658109/15221842/03803e1a-1865-11e6-98c1-2cbeb1dcbd5c.png)

**Comment by Llewellynvdm** [comment]
I think I did see this before, and there was a reason for it. I will take another look and get back to you.

**Comment by Llewellynvdm** [comment]
ah found the issue, it was a bug. I must have been wrong about having seen it before. It has now been fixed and should be resolved with the next commit to the master repository.

**Comment by distantobserver** [comment]
Yes. It's fixed on the site now. Thanks
