### ISSUE TITLE
Remove all global $_GET varubales from project.

### ISSUE THREAD

**Issue by Llewellynvdm** [Llewellynvdm/Joomla-Cost-Benefit-Projection#18]
The use of the global $_GET variable is dangerous and a possible security breach, and must be removed ASAP as per advice from @anibalsanchez

**Comment by anibalsanchez** [comment]
+1

**Comment by distantobserver** [comment]
OK. So can this be done easily without affecting the calculations?

**Comment by Llewellynvdm** [comment]
Yes this was already done, and the system is already updated with the fix.

**Comment by distantobserver** [comment]
Thanks. After posting I realised the issue is closed.
