### ISSUE TITLE
Medical Turnover Cost Factor

### ISSUE THREAD

**Issue by RachelShiweda2** [Llewellynvdm/Joomla-Cost-Benefit-Projection#19]
The tool shows that the Medical Turnover Cost Factor can only take numbers between 0 and 1. This needs to be removed, because numbers above 1 can also be entered into the tool.

**Comment by Llewellynvdm** [comment]
Matthew, please confirm this change as I clearly remember that this is how I was told it should work. It is therefore not an error but a change/ adjustment to the tool.

**Comment by Llewellynvdm** [comment]
As far as I understand 1 is a full year and any thing down is in between so how can it be more then 1 since the value is reflecting the amount of **a year** in lost productivity due to medical retirement/death of an employee.

**Comment by RachelShiweda2** [comment]
Sorry, I mend to say that the label in the tool states "Between 0 and 1" this can be a tricky, as people might think that the value which can be entered should be between 0 and 1.

**Comment by Llewellynvdm** [comment]
Okay :) 

Can you give me the complete, exact description since the one in the tool was written by Matthew or Pascal and I am not sure what should it say instead.

**Comment by RachelShiweda2** [comment]
Hi,
Can you kindly remove the label "Between 0 and 1". The label should not display anything, it should be empty. 
Thank you very much!

**Comment by Llewellynvdm** [comment]
Okay will the following be okay:

> The interim number between 00.0 and 1 reflecting the amount of a year in lost productivity due to medical retirement/death of an employee.

or should it read

> The interim number reflecting the amount of a year in lost productivity due to medical retirement/death of an employee.

**Comment by distantobserver** [comment]
The proportion of annual salary that it costs  to replace an employee for medical reasons.
