### ISSUE TITLE
Cluster Interventions

### ISSUE THREAD

**Issue by distantobserver** [Llewellynvdm/Joomla-Cost-Benefit-Projection#20]
The Cluster Interventions are not working properly. 

On the front end, once I select the interventions that form my cluster, I am not prompted to add the cost and impact reductions. Nor can I do this by returning to edit the intervention later.

On the back end. when I select the interventions box, I do not get a drop-down list of interventions from which to choose.

**Comment by Llewellynvdm** [comment]
I just tested the back-end and it works as expected, yet the front-end does have an problem. This could be due to the security fix. I will debug and update with a fix.

**Comment by distantobserver** [comment]
OK. Yes, back-end is fine. It was my error.
