### ISSUE TITLE
Videos

### ISSUE THREAD

**Issue by distantobserver** [Llewellynvdm/Joomla-Cost-Benefit-Projection#23]
Please find the videos and required annotations to be added on [dropbox](https://www.dropbox.com/sh/k0atxyki68fj2r2/AABXe5JTloBp4WVHCUAeCDjJa?dl=0)

**Comment by Llewellynvdm** [comment]
https://youtu.be/amq62a6Up3A
https://youtu.be/F-vX1bIfCs8
