### ISSUE TITLE
Scaling Factors

### ISSUE THREAD

**Issue by RachelShiweda2** [Llewellynvdm/Joomla-Cost-Benefit-Projection#3]
When I click on scaling factors the Archived causes/risks show on top while the Published causes/risks are at the bottom. Is there a possibility to change it the other way around, where Published causes/risks will be on top and the Archived ones will be at the bottom?

**Comment by Llewellynvdm** [comment]
Can you please explain more, it seems unclear... This is what I can say, the columns can sort so just clicking in the header of that status column will sort it in another direction. Then if you only what to see the Published items simply select the filter on the right for status => Published and you will only see the published items.
