### ISSUE TITLE
Cause/Risk Selection

### ISSUE THREAD

**Issue by RachelShiweda2** [Llewellynvdm/Joomla-Cost-Benefit-Projection#4]
Currently the tool allows us to select the main cause i.e. 
HIV/AIDS (A.1.) and we can select 
Tuberculosis (A.1.1.)
HIV/AIDS (A.1.2 )
HIV related infection (A.1.2.1.)
HIV related diseases (A.1.2.2)
All of the above can be selected at the same time. However this should not be. If the main cause A.1. is selctred we should not be able to select the other options

**Comment by Llewellynvdm** [comment]
Can you tell me what browser they were using? since it works well in Chrome and Firefox.

**Comment by RachelShiweda2** [comment]
They were using Chrome, I used internet explorer and it gives me the same problem.
