### ISSUE TITLE
Usage of same user account 

### ISSUE THREAD

**Issue by RachelShiweda2** [Llewellynvdm/Joomla-Cost-Benefit-Projection#6]
Two people from NUST were able to work on the same User NUST account (at the same time). We thought this was not possible. What could be the problem which causes this to happen?

**Comment by Llewellynvdm** [comment]
This is normal to the Joomla framework, and not related to the CBP tool. This is not ideal and should not be done, but if two people login with the same account the Joomla framework treats them as one.
